### ISSUE TITLE
Bug Report: unable to update & install

### ISSUE THREAD

**Issue by Niptoc** [home-assistant/supervised-installer#198]
### OS Version

Raspbian GNU/Linux 10 (buster)

### System Information

 Linux raspberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux

### What happened?

I wanted to update supervisor from a running installation but I got every time an error message.

So I tried to reinstall from scratch HA supervised (and reinstall docker also) but every time I have this error message:
`failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/7fa62dd8251695e9dfd696a06b5996dedc8b834e5d1f0c0f8af50585bf9baee5/merged: too many levels of symbolic links`

I performed the install using this command:
`sudo dpkg -i homeassistant-supervised.deb`   (method 1)
I also tried : `docker pull ghcr.io/home-assistant/armv7-hassio-supervisor:2022.02.0`   (method 2)

### Machine Type

raspberrypi3

### Installer output
```text
(Reading database ... 66625 files and directories currently installed.)
Preparing to unpack homeassistant-supervised.deb ...
[warn]
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn]
[warn] ModemManager service is enabled. This might cause issue when using serial devices.
Leaving 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised'
Leaving 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised'
Leaving 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised'
Leaving 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised'
Unpacking homeassistant-supervised (1.1.0) over (1.1.0) ...
Setting up homeassistant-supervised (1.1.0) ...
[info] Restarting NetworkManager
[info] Restarting docker service
PING version.home-assistant.io(2606:4700:20::681a:4ee (2606:4700:20::681a:4ee)) 56 data bytes
64 bytes from 2606:4700:20::681a:4ee (2606:4700:20::681a:4ee): icmp_seq=1 ttl=53 time=36.4 ms

--- version.home-assistant.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 36.435/36.435/36.435/0.000 ms
Device "eth0
wlan0" does not exist.
[info] Install supervisor Docker container
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/7bf5153ef289a3123709f9797cf828c5516dbfcdcb91f57cc604d4386481bc2c/merged: too many levels of symbolic links
dpkg: error processing package homeassistant-supervised (--install):
 installed homeassistant-supervised package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 homeassistant-supervised
```

### Docker pull output

```text
docker pull ghcr.io/home-assistant/armv7-hassio-supervisor:2022.02.0
2022.02.0: Pulling from home-assistant/armv7-hassio-supervisor
764d2e53e1a6: Already exists
d8f4f3181267: Already exists
0fada6d110d1: Already exists
2ccff4486b79: Already exists
d5c807944aaf: Already exists
f3e296d9ca8b: Already exists
a633e7ce2b4d: Already exists
16ba1aa63021: Already exists
3daa7301285a: Extracting [==================================================>]     423B/423B
5457394f0490: Download complete
3a727f59f15c: Download complete
96c4f5494f18: Download complete
94ae4870cce2: Download complete
failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/7fa62dd8251695e9dfd696a06b5996dedc8b834e5d1f0c0f8af50585bf9baee5/merged: too many levels of symbolic links
```

### Relevant log output method 1
```shell
-- Logs begin at Thu 2022-03-17 09:19:13 CET. --
Mar 17 17:36:02 raspberrypi 508b0f86c1c5[21763]: [cont-init.d] executing container initialization scripts...
Mar 17 17:36:02 raspberrypi 508b0f86c1c5[21763]: [cont-init.d] done.
Mar 17 17:36:02 raspberrypi 508b0f86c1c5[21763]: [services.d] starting services
Mar 17 17:36:02 raspberrypi 508b0f86c1c5[21763]: [services.d] done.
Mar 17 17:36:05 raspberrypi dockerd[21763]: time="2022-03-17T17:36:05.385719919+01:00" level=error msg="error unmounting /var/lib/docker/overlay2/7bf5153ef289a3123709f9797cf828c5516dbfcdcb91f57cc604d4386481bc2c/merged: invalid argument" storage-driver=overlay2
Mar 17 17:36:05 raspberrypi kernel: overlayfs: overlapping lowerdir path
Mar 17 17:36:08 raspberrypi systemd[1]: NetworkManager-dispatcher.service: Succeeded.
Mar 17 17:36:19 raspberrypi dockerd[21763]: time="2022-03-17T17:36:19.509044655+01:00" level=info msg="Attempting next endpoint for pull after error: failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/7bf5153ef289a3123709f9797cf828c5516dbfcdcb91f57cc604d4386481bc2c/merged: too many levels of symbolic links"
Mar 17 17:36:19 raspberrypi sudo[21526]: pam_unix(sudo:session): session closed for user root
Mar 17 17:36:22 raspberrypi systemd[1]: systemd-hostnamed.service: Succeeded.
```

### Relevant log output method 2
```shell
-- Logs begin at Thu 2022-03-17 09:19:13 CET. --
Mar 17 17:27:31 raspberrypi dbus-daemon[21473]: [session uid=1000 pid=21473] Successfully activated service 'org.freedesktop.secrets'
Mar 17 17:27:38 raspberrypi dockerd[20999]: time="2022-03-17T17:27:38.916120756+01:00" level=error msg="error unmounting /var/lib/docker/overlay2/7fa62dd8251695e9dfd696a06b5996dedc8b834e5d1f0c0f8af50585bf9baee5/merged: invalid argument" storage-driver=overlay2
Mar 17 17:27:38 raspberrypi kernel: overlayfs: overlapping lowerdir path
Mar 17 17:27:53 raspberrypi dockerd[20999]: time="2022-03-17T17:27:53.063655571+01:00" level=info msg="Attempting next endpoint for pull after error: failed to register layer: error creating overlay mount to /var/lib/docker/overlay2/7fa62dd8251695e9dfd696a06b5996dedc8b834e5d1f0c0f8af50585bf9baee5/merged: too many levels of symbolic links"
Mar 17 17:31:17 raspberrypi 508b0f86c1c5[20999]: 2022-03-17 17:31:17 ERROR (MainThread) [aiohttp.server] Error handling request
Mar 17 17:31:17 raspberrypi 508b0f86c1c5[20999]: Traceback (most recent call last):
Mar 17 17:31:17 raspberrypi 508b0f86c1c5[20999]:   File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
Mar 17 17:31:17 raspberrypi 508b0f86c1c5[20999]:     messages, upgraded, tail = self._request_parser.feed_data(data)
Mar 17 17:31:17 raspberrypi 508b0f86c1c5[20999]:   File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
Mar 17 17:31:17 raspberrypi 508b0f86c1c5[20999]: aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
```

### ADR

- [X] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by Niptoc** [comment]
Hello,

It is working fine now... It seems I had an issue in docker config file. 
I had to totally remove docker.
- Uninstall with `apt remove --purge docker-ce docker-ce-cli docker-compose containerd.io`
- remove residual files: `$ sudo rm -rf /var/lib/docker/   ` 

Note: the uninstall & purge was not enough to solve my issue.
