### ISSUE TITLE
Bug Report: CGroup v1 is now deprecated

### ISSUE THREAD

**Issue by rokam** [home-assistant/supervised-installer#372]
### OS Version

Arch Linux

### System Information

Linux pclucas 6.9.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:37 +0000 x86_64 GNU/Linux

### What happened?

Systemd have deprecated cgroup v1, although it is still able to use v1 adding another kernel parameter. It'll still work for Debian 11, but I think the migration to v2 should be planned.
https://github.com/systemd/systemd/issues/30852

### Machine Type

generic-x86-64

### ADR

- [ ] I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
- [X] I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation

### Code of Conduct

- [X] I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)

**Comment by frostworx** [comment]
Thanks for opening this issue.

I also opened a thread on community side:

https://community.home-assistant.io/t/cgroupsv1-no-longer-supported-by-systemd/742098

**Comment by frostworx** [comment]
what is your current workaround @rokam?
provide  `systemd.unified_cgroup_hierarchy=false SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE=1 `
via cmdline as well _(and wait additional 30 seconds because this should be removed)_?

If so do home assistant logs work for you currently? all my home assistant logs are broken currently,
because the supervisor logs crash with

```
Jul 15 15:56:32 mini hassio_supervisor[1135]: 2024-07-15 15:56:32.898 ERROR (MainThread) [aiohttp.server] Error handling request
Jul 15 15:56:32 mini hassio_supervisor[1135]: Traceback (most recent call last):
Jul 15 15:56:32 mini hassio_supervisor[1135]:   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
Jul 15 15:56:32 mini hassio_supervisor[1135]:     resp = await request_handler(request)
Jul 15 15:56:32 mini hassio_supervisor[1135]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 15:56:32 mini hassio_supervisor[1135]:   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
Jul 15 15:56:32 mini hassio_supervisor[1135]:     resp = await handler(request)
Jul 15 15:56:32 mini hassio_supervisor[1135]:            ^^^^^^^^^^^^^^^^^^^^^^
Jul 15 15:56:32 mini hassio_supervisor[1135]:   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
Jul 15 15:56:32 mini hassio_supervisor[1135]:     return await handler(request)
Jul 15 15:56:32 mini hassio_supervisor[1135]:            ^^^^^^^^^^^^^^^^^^^^^^
Jul 15 15:56:32 mini hassio_supervisor[1135]:   File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 189, in block_bad_requests
Jul 15 15:56:32 mini hassio_supervisor[1135]:     return await handler(request)
Jul 15 15:56:32 mini hassio_supervisor[1135]:            ^^^^^^^^^^^^^^^^^^^^^^
Jul 15 15:56:32 mini hassio_supervisor[1135]:   File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 205, in system_validation
Jul 15 15:56:32 mini hassio_supervisor[1135]:     return await handler(request)
Jul 15 15:56:32 mini hassio_supervisor[1135]:            ^^^^^^^^^^^^^^^^^^^^^^
Jul 15 15:56:32 mini hassio_supervisor[1135]:   File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 272, in token_validation
Jul 15 15:56:32 mini hassio_supervisor[1135]:     return await handler(request)
Jul 15 15:56:32 mini hassio_supervisor[1135]:            ^^^^^^^^^^^^^^^^^^^^^^
Jul 15 15:56:32 mini hassio_supervisor[1135]:   File "/usr/src/supervisor/supervisor/api/middleware/security.py", line 283, in core_proxy
Jul 15 15:56:32 mini hassio_supervisor[1135]:     return await handler(request)
Jul 15 15:56:32 mini hassio_supervisor[1135]:            ^^^^^^^^^^^^^^^^^^^^^^
Jul 15 15:56:32 mini hassio_supervisor[1135]:   File "/usr/src/supervisor/supervisor/api/utils.py", line 103, in wrap_api
Jul 15 15:56:32 mini hassio_supervisor[1135]:     msg_data = await method(api, *args, **kwargs)
Jul 15 15:56:32 mini hassio_supervisor[1135]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 15:56:32 mini hassio_supervisor[1135]:   File "/usr/src/supervisor/supervisor/api/host.py", line 227, in advanced_logs
Jul 15 15:56:32 mini hassio_supervisor[1135]:     return await self.advanced_logs_handler(request, identifier, follow)
Jul 15 15:56:32 mini hassio_supervisor[1135]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 15:56:32 mini hassio_supervisor[1135]:   File "/usr/src/supervisor/supervisor/api/host.py", line 214, in advanced_logs_handler
Jul 15 15:56:32 mini hassio_supervisor[1135]:     async for line in journal_logs_reader(resp, log_formatter):
Jul 15 15:56:32 mini hassio_supervisor[1135]:   File "/usr/src/supervisor/supervisor/utils/systemd_journal.py", line 98, in journal_logs_reader
Jul 15 15:56:32 mini hassio_supervisor[1135]:     length_raw = await resp.content.readexactly(8)
Jul 15 15:56:32 mini hassio_supervisor[1135]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 15:56:32 mini hassio_supervisor[1135]:   File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 452, in readexactly
Jul 15 15:56:32 mini hassio_supervisor[1135]:     raise asyncio.IncompleteReadError(partial, len(partial) + n)
Jul 15 15:56:32 mini hassio_supervisor[1135]: asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 8 expected bytes
```

triggered both via `ha supervisor logs` or clicking any log/protocol in HA.

would be interesting if cgroups v1 causes this on "brandnew" systems which require the ugly`SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE` workaround

**Comment by rokam** [comment]
I'm not using arch anymore. But that cmdline is the way

**Comment by frostworx** [comment]
yeah, the cmdline works "fine" for now at least.

sad to hear you left Arch - seems like I'm the only one left with this problem now ;)

**Comment by rokam** [comment]
It seems that the supervisor already supports v2. Would you be able to remove it from the kernel cmdline?

**Comment by frostworx** [comment]
thank you for trying to help!

It would explain why nobody has that problem, but
https://www.home-assistant.io/more-info/unsupported/cgroup_version/
still suggests to use cgroup v1.
just digging though supervised-installer trying to find something.

**Comment by frostworx** [comment]
As there don't seem to be any apparent plans to change the situation, I hope using v2 doesn't break my whole HA functionality.

`"Please understand that support for cgroupv1 is going to go away entirely very very soon now."`

[via](https://github.com/systemd/systemd/issues/30852#issuecomment-2200617115)

doesn't look like there's much time left to wait.

**Comment by agners** [comment]
We do use cgroupsv2 in HAOS, it works quite well.

There is one feature of the Supervisor which used to update device permissions directly via CGroupsV1 (see https://github.com/home-assistant/supervisor/pull/3421). Unfortunately, the way this was implemented broke with CGroupsV2, and it was not straight forward to implement it in a similar fashion.

Eventually, I've added device permissino update for CGroupsV2 via runc/containerd changes (see https://github.com/home-assistant/os-agent/pull/92 and https://github.com/opencontainers/runc/pull/3402). However, this change did not made it upstream yet to runc/containerd, so it remains a feature of the patched version in HAOS :cry: 

I've pinged folks again in https://github.com/opencontainers/runc/pull/3402, let's see. If someone is connected to the containerd/OCI community, I'd be glad if you can make things move forward.

**Comment by frostworx** [comment]
Thank you very much for the heads-up, @agners. Very appreaciated!

**Comment by frostworx** [comment]
[doesn't look fixed](https://www.home-assistant.io/more-info/unsupported/cgroup_version/)

**Comment by hbiyik** [comment]
systemd is really blackmailing my system with an extra 30s of delay with the force kernel argument  `SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE=1` it is really really annying.

**Comment by atostivint** [comment]
Personally, I also gave up and disabled cgroupv1. Nothing changed on my side.

**Comment by agners** [comment]
> systemd is really blackmailing my system with an extra 30s of delay with the force kernel argument `SYSTEMD_CGROUP_ENABLE_LEGACY_FORCE=1` it is really really annying.
> 
> https://github.com/systemd/systemd/blob/727dc1f23a2e16da7f1e24810157d5b7c9136525/src/core/main.c#L3186

Is that shipped in Debian Bookworm already? :thinking: 

We kinda have to move away from cgroupsv1, I guess we just need to accept that upstream is not interested in dynamic device permission settings for cgroupsv2 and live with the consequences: Supervised installations won't have support for dynamic hardware update :cry:

**Comment by hbiyik** [comment]
> Is that shipped in Debian Bookworm already? 🤔

i am on arch, i think rolling distros are impacted first.

**Comment by frostworx** [comment]
good to see some motion here, thanks all.

_(personally I disabled cgroups v1, but would be nice to get proper logging back one day)_

**Comment by agners** [comment]
> _(personally I disabled cgroups v1, but would be nice to get proper logging back one day)_

What do you mean by proper logging? :thinking:

**Comment by frostworx** [comment]
> > _(personally I disabled cgroups v1, but would be nice to get proper logging back one day)_
> 
> What do you mean by proper logging? 🤔

hm, all my home assistant logs are empty since I dropped cgroups v1.
I assumed this was related, but now after you ask I'm no longer sure it is :)
Didn't care that much and simply read the cointainer logs when I needed to.
So thank you for asking :)

**Comment by agners** [comment]
> hm, all my home assistant logs are empty since I dropped cgroups v1.

That is more likely because we changed to fetch logs directly from `systemd-journald` through `systemd-journal-gatewayd`. See [this](https://github.com/home-assistant/supervised-installer/blob/f52ff8259e99f3d4872633e4dc740f85c1db5f2d/homeassistant-supervised/DEBIAN/postinst#L43) and [this](https://github.com/home-assistant/supervised-installer/blob/f52ff8259e99f3d4872633e4dc740f85c1db5f2d/homeassistant-supervised/etc/systemd/system/systemd-journal-gatewayd.socket.d/10-hassio-supervisor.conf#L2).

**Comment by frostworx** [comment]
oh, thank you very much for your help, @agners!

Very likely the problem lies in gatewayd - haven't touched/looked into it since it worked. sorry for the offtopic noise all

**Comment by frostworx** [comment]
Seems like nothing changed here, [the documentation](https://www.home-assistant.io/more-info/unsupported/cgroup_version/) still suggests to revert to dead cgroupv1, so I suggest a reopen here.

My addon logging problems mentioned above (500 Internal Server Error) seem to be Arch related (found some stray Arch threads, but no url ready for now), which makes me guess that the problem is caused by a not up2date homeassistant-supervised package. The package hast a pinned comment about missing cgroupv2 support (which likely is the reason for the package not being bumped).

*bumping this thread and the package discussion simultaneously*

**Comment by agners** [comment]
Actually, [Supervisor 2024.12.0](https://github.com/home-assistant/supervisor/releases/tag/2024.12.0) contains #5419, so CGroupsV2 should no longer mark a Supervised installation as unsupported.

So this means you can use CGroupsV2 on Supervised installations. The only downside will be that hot-plugging of tty devices won't work *if* the add-on uses the above mentioned syntax. However, I think most add-ons nowadays use the more modern way of using the `schema` tag and a config of type `device(subsystem=tty)` (like OpenThread Border Router etc.) or `uart: true` (e.g. Z2M).

**Comment by agners** [comment]
> Maybe I didn't follow this close enough, but I guess several other people are still sitting on cgroupv1 for having missed the news as well.

Yes I'd expect pretty much everyone to be still on cgroupsv1 at this point.

I think the next step would be to update the installer to no longer switch to cgroupsv1, so that new installations are no longer affected.

As for migrating existing installation, I am not sure how we handled this so far. I guess we *could* make the deb installation script to revert what has been done previously :thinking:  @ikifar2012 any thoughts on this?

**Comment by ikifar2012** [comment]
@agners I have updated the script to revert changes, please take a look at PR #391 and let me know what you think

**Comment by ikifar2012** [comment]
This issue should be resolved with version 3.0.0:
https://github.com/home-assistant/supervised-installer/releases/tag/3.0.0

You will be required to restart your system for changes to take affect 

I will be closing this issue but please feel free to open a new issue if there are any problems with this change
