### ISSUE TITLE
Installation hassio on centos 8 not working

### ISSUE THREAD

**Issue by pavkamlc** [home-assistant/supervised-installer#98]
Installation on centos 8 not working.
I tried with podman, and docker-ce too, script don't work always.
There is some problems:
1) Script isn't described as debian distribution only, but it seems works only on this distros
2) hassio-supervisor.service required docker.service
3) manually start /usr/sbin/hassio-supervisor don't works too

_[root@home etc]# curl -sL https://raw.githubusercontent.com/home-assistant/supervised-installer/master/installer.sh | bash -s
[Warning] No AppArmor support on host.
[Info] Install supervisor Docker container
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Trying to pull registry.access.redhat.com/homeassistant/amd64-hassio-supervisor:217...
  name unknown: Repo not found
Trying to pull registry.fedoraproject.org/homeassistant/amd64-hassio-supervisor:217...
  manifest unknown: manifest unknown
Trying to pull registry.centos.org/homeassistant/amd64-hassio-supervisor:217...
  manifest unknown: manifest unknown
Trying to pull docker.io/homeassistant/amd64-hassio-supervisor:217...
Getting image source signatures
Copying blob 0cf3ea2876d5 skipped: already exists
Copying blob aad63a933944 skipped: already exists
Copying blob 1368f36d21e4 skipped: already exists
Copying blob 38a6ebd7137f skipped: already exists
Copying blob d71aebdd69cc skipped: already exists
Copying blob 2392dab50ea9 skipped: already exists
Copying blob e6fe9169e422 skipped: already exists
Copying blob b180f7a57f63 skipped: already exists
Copying blob ca1c56d68945 skipped: already exists
Copying blob 56a4e88e2d53 skipped: already exists
Copying blob 22aa3035d255 skipped: already exists
Copying blob 1b80ba158a81 skipped: already exists
Copying blob b46f5391cfa0 skipped: already exists
Copying blob 83e3c21585f9 skipped: already exists
Copying config a0a860227f done
Writing manifest to image destination
Storing signatures
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
[Info] Install supervisor startup scripts
[Info] Run Hass.io
Failed to start hassio-supervisor.service: Unit docker.service not found.
[root@home etc]# docker image list
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
REPOSITORY                                        TAG      IMAGE ID       CREATED       SIZE
docker.io/homeassistant/amd64-hassio-supervisor   217      a0a860227f9e   10 days ago   336 MB
localhost/homeassistant/amd64-hassio-supervisor   latest   a0a860227f9e   10 days ago   336 MB
[root@home etc]# docker container list
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE  COMMAND  CREATED  STATUS  PORTS  NAMES
[root@home etc]#_ 

_root@home etc]# /usr/sbin/hassio-supervisor 
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: error getting image "hassio_supervisor": unable to find a name and tag match for hassio_supervisor in repotags: no such image
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: Failed to evict container: "": Failed to find container "hassio_supervisor" in state: no container with name or ID hassio_supervisor found: no such container
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
[12:47:33] INFO: Update udev informations
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
20-04-22 12:47:38 INFO (MainThread) [supervisor.bootstrap] Use the old homeassistant repository for machine extraction
20-04-22 12:47:38 INFO (MainThread) [__main__] Initialize Supervisor setup
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 207, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/local/lib/python3.7/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/supervisor/supervisor/__main__.py", line 40, in <module>
    coresys = loop.run_until_complete(bootstrap.initialize_coresys())
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/src/supervisor/supervisor/bootstrap.py", line 50, in initialize_coresys
    coresys = CoreSys()
  File "/usr/src/supervisor/supervisor/coresys.py", line 56, in __init__
    self._docker: DockerAPI = DockerAPI()
  File "/usr/src/supervisor/supervisor/docker/__init__.py", line 34, in __init__
    base_url="unix:/{}".format(str(SOCKET_DOCKER)), version="auto", timeout=900
  File "/usr/local/lib/python3.7/site-packages/docker/client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 190, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 215, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
20-04-22 12:47:38 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fc409042ed0>
20-04-22 12:47:38 ERROR (MainThread) [asyncio] Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fc408e01050>
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting._

**Comment by pvizeli** [comment]
![image](https://user-images.githubusercontent.com/15338540/80027019-65e26580-84e3-11ea-8b96-9c5fc0c28449.png)
